# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67e042d837b3fbd44b1e38d43b358b00be735a2424859678a08de9cddf0c28e76d8dd66bbdcf4874128b3f45f849240025a3e5ab06bd0e11a56e1e9f7383c035

test:
  secret_key_base: b0ae958f39aa936ce6fc12a2942d374d0b9b24a6cbabfb6c00509bf0e01a029b9609bdd1f9827223bfa877cf386a4b105485f343bdb88fc46defd720da3bce3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
